
[package]
name = "syntax-fuzz"
version = "0.0.1"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
syntax = { path = "..", version = "0.0.0" }
text-edit = { path = "../../text-edit", version = "0.0.0" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"

[[bin]]
name = "reparse"
path = "fuzz_targets/reparse.rs"
